apps/siiges-app/pages/_app.jsx
apps/siiges-app/pages/index.jsx
apps/siiges-app/pages/institucion/index.jsx
package.json
packages/authentication/src/components/SignIn/index.jsx
packages/authentication/src/users.json
packages/instituciones/src/components/Institucion/index.jsx
packages/shared/__tests__/components/Input/input.test.jsx
packages/shared/__tests__/components/Input/inputPassword.test.jsx
packages/shared/__tests__/components/Navbar/mainNavbar.test.jsx
packages/shared/__tests__/components/Navbar/menuNavbar.test.jsx
packages/shared/__tests__/pages/Login/login.test.jsx
packages/shared/src/components/Drawer/MenuDrawer.jsx
packages/shared/src/components/Drawer/utils/drawer.js
packages/shared/src/components/HomePage/index.jsx
packages/shared/src/components/Input/inputPassword.jsx
packages/shared/src/components/Navbar/menuNavbar.jsx
packages/shared/src/index.js
packages/shared/src/utils/handlers/context.jsx
packages/shared/src/utils/handlers/cookieHandler.js
packages/solicitudes/src/components/ModuleSelector/CambioDomicilio/index.jsx
packages/solicitudes/src/components/ModuleSelector/NuevaSolicitud/index.jsx
yarn.lock

First failed attempt at adding cookies for the session

feat: added cookies for auth

---

apps/siiges-app/next.config.js
apps/siiges-app/package.json
apps/siiges-app/pages/inspecciones/asignacionInspecciones/index.jsx
apps/siiges-app/pages/inspecciones/index.jsx
packages/authentication/src/users.json
packages/inspecciones/README.md
packages/inspecciones/__tests__/inspecciones.test.js
packages/inspecciones/package.json
packages/inspecciones/src/components/FormAsignacionInspecciones/index.jsx
packages/inspecciones/src/components/InspeccionesTable/index.jsx
packages/inspecciones/src/components/Mocks/Inspecciones.js
packages/inspecciones/src/components/Mocks/inspectores.js
packages/inspecciones/src/index.js
packages/shared/src/components/Buttons/ButtonsForm.jsx
packages/shared/src/components/Drawer/MenuDrawer.jsx

Desktop web versions of inspecciones related to #22

feat(inspecciones): added the initial views of inspecciones

---

packages/shared/src/components/Select/index.jsx

fix(shared): fixed how the select displays label

---

packages/instituciones/src/components/Planteles/newPlantelForm.jsx
packages/instituciones/src/components/utils/submitEditPlantel.js
packages/instituciones/src/components/utils/submitNewPlantel.js

small fix to submit new plantel

fix(planteles): fixed the new plantel functions

---

packages/instituciones/src/components/Planteles/consultPlantelesForm.jsx
packages/instituciones/src/components/Planteles/editPlantelForm.jsx
packages/instituciones/src/components/utils/plantelErrors.js

fixed error when thers no director assigned on plantel while consulting

fix(instituciones): fixed error when thers no director

---

packages/instituciones/src/components/Planteles/index.jsx
packages/instituciones/src/components/utils/deletePlantel.jsx

fix(planteles): fixed the issue that prevented from deleting plantel

---

packages/instituciones/src/components/Planteles/newPlantelForm.jsx
packages/instituciones/src/components/utils/plantelErrors.js

fix(plantel): fixed validations when editing a plantel

---

packages/instituciones/src/components/utils/plantelErrors.js

Hopefully last iteration of this issue

fix(planteles): fixed issues between edit and new plantel

---

.eslintrc.js
apps/siiges-app/pages/solicitudes/index.jsx
packages/shared/src/components/Input/index.jsx
packages/shared/src/components/Navbar/mainnavbar.jsx
packages/shared/src/components/Select/index.jsx
packages/solicitudes/src/components/ModuleSelector/NuevaSolicitud/index.jsx
packages/solicitudes/src/components/Sections/DatosPlanEstudios.jsx
packages/solicitudes/src/components/utils/Mocks/mockModalidades.js
packages/solicitudes/src/components/utils/getPlantelesUsuario.jsx
packages/solicitudes/src/components/utils/sections/errors/errorDatosNuevaSolicitud.js
packages/solicitudes/src/components/utils/sections/errors/errorDatosPlanEstudios.js
packages/solicitudes/src/components/utils/sections/forms/formData.js
packages/solicitudes/src/index.js

validaciones de inicio completas

feat(solicitudes): completadas validaciones para generar solicitud

---

apps/siiges-app/pages/institucion/nuevaInstitucion/index.jsx
apps/siiges-app/pages/institucion/utils/createInstitucion.jsx
packages/instituciones/src/components/Institucion/editInstitutionForm.jsx
packages/instituciones/src/components/Institucion/newInstitutionForm.jsx
packages/instituciones/src/components/utils/errorDatosNewInstitucion.js
packages/instituciones/src/components/utils/getInstitucionUsuario.jsx
packages/solicitudes/src/index.js

PR fix of instituciones view and create

fix(instituciones): fixed create institucion

---

packages/solicitudes/src/components/Sections/Mocks/Asignaturas/index.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasButtons.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasModales/AsignaturasEditModal.jsx
packages/solicitudes/src/components/utils/submitEditAsignaturas.jsx

edit and consult functions on asignaturas fixed

fix(asignaturas): fixed edit and consult functions

---

packages/shared/src/components/DataTable/index.jsx

Added filtering functionality, all column data is filtered, omitting null data. When there is nothing in the search bar it returns to default values.

feat(institucion):filter

---

packages/shared/src/components/DataTable/index.jsx
packages/solicitudes/src/components/utils/getSolicitudes.jsx

corrección de los filtros en las datatables

fix(tables): fixed the tables filters

---

apps/siiges-app/pages/institucion/[institucionId]/editarInstitucion/index.jsx
apps/siiges-app/pages/institucion/utils/updateInstitucion.jsx
packages/instituciones/src/components/Institucion/editInstitutionForm.jsx

SDT: 90
Ya funciona editar Institucion, sin embargo aun hay problemas a la hora de checar si los datos son correctos y por alguna razon funciona al segundo click de haber puesto los datos que se desean

feat(institucion): editar institucion

---

apps/siiges-app/pages/serviciosEscolares/index.jsx
packages/serviciosEscolares/package.json

Fixed issues where build crashed because a servicio escolar import

fix(serviciosescolares): fixed minor issues for build

---

apps/siiges-app/pages/solicitudes/detallesSolicitudes/[id]/index.jsx
apps/siiges-app/pages/solicitudes/index.jsx
packages/instituciones/src/components/Institucion/editInstitutionForm.jsx
packages/instituciones/src/components/Institucion/newInstitutionForm.jsx

vistas detalles de la solicitud

feat(solicitud): added detalles solicitud

---

packages/serviciosEscolares/src/Components/utils/CiclosEscolaresModal.jsx
packages/solicitudes/src/components/Sections/DatosPlanEstudios.jsx
packages/solicitudes/src/components/utils/getSolicitudesById.jsx
packages/solicitudes/src/components/utils/submitNewSolicitud.jsx

correcciones del campo "nivel" en solicitudes, y una correccion menor de importacion en "Servicios Escolares"

feat(solicitudes): fixed issues with nivel

---

apps/siiges-app/pages/opds/organosColegiados/[id]/editar/index.jsx
packages/opds/src/components/organosColegiados/Form/organosColegiados.jsx
packages/opds/src/components/organosColegiados/Tables/ButtonsOrganosColegiados.jsx
packages/opds/src/index.js
packages/opds/src/utils/organosColegiados/Tables/columnsOrganosColegiados.jsx

feat(opds): changes to edit opds

---

apps/siiges-app/pages/opds/presupuesto/index.jsx
packages/shared/src/components/Buttons/Button.jsx
packages/shared/src/components/Buttons/ButtonIcon.jsx

boton de guardar presupuesto añadido

feat(opds): added button to presupuesto and some minor bugfixes

---

packages/shared/src/components/Drawer/utils/userRol.jsx

feat(opds): added the menu to opds rol

---

packages/instituciones/src/utils/getAlumnoByMatricula.jsx
packages/instituciones/src/utils/getAsignaturas.jsx
packages/instituciones/src/utils/getInscripcionesAlumnos.jsx
packages/instituciones/src/utils/updateInstitucion.jsx
packages/solicitudes/src/components/NuevaSolicitud/PlanEstudios/index.jsx
packages/solicitudes/src/components/SectionLayout/ButtonSection.jsx
packages/solicitudes/src/components/utils/submitNewSolicitud.jsx
packages/solicitudes/src/components/utils/submitTrayectoriaeducativa.jsx

feat(solicitudes): fixed issues with solicitudes

---

packages/instituciones/src/components/utils/getInstitucionUsuario.jsx
packages/shared/src/utils/handlers/validateField.js
packages/solicitudes/src/components/SectionLayout/ButtonSection.jsx
packages/solicitudes/src/components/Sections/DiligenciasData.jsx
packages/solicitudes/src/components/Sections/InstitucionData.jsx
packages/solicitudes/src/components/Sections/Mocks/Diligencias/index.jsx
packages/solicitudes/src/components/Sections/RepresentanteLegalData.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasFormacionModales/AsignaturasFormacionCreateModal.jsx
packages/solicitudes/src/components/utils/Components/DiligenciasButtons.jsx
packages/solicitudes/src/components/utils/Components/DiligenciasModales/DiligenciasEditModal.jsx
packages/solicitudes/src/components/utils/Components/DiligenciasModales/DiligenciasFormModal.jsx
packages/solicitudes/src/components/utils/Components/DiligenciasToRows.js
packages/solicitudes/src/components/utils/Context/datosGeneralesContext.jsx
packages/solicitudes/src/components/utils/sections/errors/errorDatosDiligencias.js
packages/solicitudes/src/components/utils/submitEditDiligencias.jsx
packages/solicitudes/src/components/utils/submitNewDiligencias.jsx

fixed issues with Datos Generales

feat(solicitudes): fixed Datos generales

---

packages/solicitudes/src/components/NuevaSolicitud/index.jsx
packages/solicitudes/src/components/SectionLayout/ButtonSection.jsx
packages/solicitudes/src/components/utils/Context/observacionesContext.jsx

PR con correcciones de emergencia de observaciones, no permitía avanzar de modulo

feat(observaciones): emergency fix

---

packages/solicitudes/src/components/NuevaSolicitud/Anexos/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/index.jsx
packages/solicitudes/src/components/Sections/AnexosSeccion.jsx

feat(solicitudes): fixed anexos issues

---

packages/shared/src/components/Input/InputDateTime.jsx
packages/shared/src/components/Input/InputNumber.jsx
packages/shared/src/index.js
packages/shared/src/utils/handlers/getFile.js
packages/solicitudes/src/components/NuevaSolicitud/EvaluacionCurricular/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/Plantel/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/index.jsx
packages/solicitudes/src/components/Sections/DatosGeneralesEvaluacion.jsx
packages/solicitudes/src/components/Sections/DescripcionPlantel.jsx
packages/solicitudes/src/components/Sections/HigienePlantel.jsx
packages/solicitudes/src/components/Sections/Infraestructura.jsx
packages/solicitudes/src/components/Sections/NombresPropuestos.jsx
packages/solicitudes/src/components/utils/Context/plantelContext.jsx
packages/solicitudes/src/components/utils/sections/errors/errorDatosGeneralesEvaluacion.js
packages/solicitudes/src/components/utils/submitEvaluacionCurricular.jsx
packages/solicitudes/src/components/utils/submitRatificacion.jsx

Solucionados problemas menores en planteles y evaluacion curricular

feat(solicitudes): fixed issues on planteles and evaluacion

---

apps/siiges-app/pages/home/index.jsx
packages/authentication/src/components/SignIn/index.jsx
packages/authentication/src/utils/submitNewLogin.js
packages/shared/src/components/Layout/Layout.jsx
packages/solicitudes/src/components/Sections/Docentes.jsx
packages/solicitudes/src/components/Sections/HigienePlantel.jsx
packages/solicitudes/src/components/Sections/Infraestructura.jsx
packages/solicitudes/src/components/Sections/Mocks/Infraestructura/index.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasFormacionModales/AsignaturasFormacionCreateModal.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasFormacionModales/AsignaturasFormacionEditModal.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasModales/AsignaturasCreateModal.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasModales/AsignaturasEditModal.jsx
packages/solicitudes/src/components/utils/Components/DiligenciasModales/DiligenciasFormModal.jsx
packages/solicitudes/src/components/utils/Components/DocentesModales/DocentesModal.jsx
packages/solicitudes/src/components/utils/Components/InfraestructuraModales/InfraestructuraCreateModal.jsx
packages/solicitudes/src/components/utils/Components/InfraestructuraModales/InfraestructuraEditModal.jsx
packages/solicitudes/src/components/utils/Components/InfraestructurasButtons.jsx
packages/solicitudes/src/components/utils/Components/InstitucionesAledanas/InstitucionesAledanasCreateModal.jsx
packages/solicitudes/src/components/utils/sections/errors/errorDatosInfraestructuras.js
packages/solicitudes/src/components/utils/submitDocentes.jsx
packages/solicitudes/src/components/utils/submitEditAsignaturas.jsx
packages/solicitudes/src/components/utils/submitEditDiligencias.jsx
packages/solicitudes/src/components/utils/submitNewAsignaturas.jsx
packages/solicitudes/src/components/utils/submitNewDiligencias.jsx
packages/solicitudes/src/components/utils/submitNewInstitucionAledanas.jsx

arreglos en infraestructura y higiene

feat(solicitudes): fixed infraestructuras and higienes

---

packages/solicitudes/src/components/Sections/InstitucionesAledanas.jsx
packages/solicitudes/src/components/utils/Components/InfraestructuraModales/InfraestructuraCreateModal.jsx
packages/solicitudes/src/components/utils/Components/InstitucionesAledanas.jsx
packages/solicitudes/src/components/utils/Components/InstitucionesAledanas/InstitucionAledanaEditModal.jsx
packages/solicitudes/src/components/utils/sections/errors/errorDatosInfraestructuras.js
packages/solicitudes/src/components/utils/submitEditInstitucionAledana.jsx
packages/solicitudes/src/components/utils/submitNewInfraestructuras.jsx

correcciones solicitudes, pantalla carga, suplicacion valores, y correcciones a planteles aledaños

fix(solicitudes): fixed value duplications

---

apps/siiges-app/pages/solicitudes/index.jsx
packages/solicitudes/src/components/utils/Components/SolicitudesActions/index.jsx
packages/solicitudes/src/components/utils/getSolicitudes.jsx

correciones a la tabla de solicitudes

feat(solicitudes): fixed solicitudes tablas for revision documental

---

apps/siiges-app/pages/solicitudes/detallesSolicitudes/[id]/editarSolicitud/index.jsx
apps/siiges-app/pages/solicitudes/nuevaSolicitud/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/Anexos/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/DatosGenerales/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/EvaluacionCurricular/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/PlanEstudios/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/Plantel/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/PlataformaEducativa/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/index.jsx
packages/solicitudes/src/components/SectionLayout/ButtonSection.jsx
packages/solicitudes/src/components/SectionLayout/index.jsx

feat(solicitudes): fixed loading state on solicitudes

---

apps/siiges-app/pages/solicitudes/detallesSolicitudes/[id]/recepcionFormatos/index.jsx
packages/shared/src/components/Buttons/ButtonFile.jsx
packages/shared/src/index.js

feat(formatos): added buttons to recepcion formatos

---

packages/users/src/components/Usuarios/UsuarioForm/index.jsx

pr sencillo, añade descripción de los requerimientos de contraseña

fix(usuarios): requerimientos contrasena agregados

---

packages/shared/src/components/Input/index.jsx

feat(shared): added character value to input

---

packages/solicitudes/src/components/utils/Components/DocentesButtons.jsx
packages/solicitudes/src/components/utils/Components/DocentesModales/DeleteDocentes.jsx

feat(docentes): added delete docentes

---

apps/siiges-app/pages/inspecciones/misInspecciones/index.jsx
packages/inspecciones/src/components/ActaCierre/index.jsx
packages/inspecciones/src/components/Mocks/misInspecciones.jsx
packages/inspecciones/src/index.js
packages/shared/src/components/Drawer/utils/menuUsers.jsx

Pendiente implementación de endpoints

feat(solicitudes): pantallas y menus de inspector

---

apps/siiges-app/pages/solicitudes/index.jsx
packages/instituciones/src/utils/getProgramas.jsx
packages/serviciosEscolares/src/Components/Programas/ProgramasForm/index.jsx
packages/serviciosEscolares/src/Components/Programas/ProgramasTable/index.jsx
packages/serviciosEscolares/src/Tables/programas.jsx
packages/solicitudes/src/components/utils/Tables/solicitudesColumns.jsx

feat(programas): minor changes to programas

---

packages/shared/src/components/Input/InputDate.jsx
packages/solicitudes/src/components/utils/Components/DocentesModales/DocentesModal.jsx

feat(solicitudes): fixed error on docentes

---

apps/siiges-app/pages/solicitudes/index.jsx
packages/inspecciones/src/components/InspeccionesTable/index.jsx
packages/solicitudes/src/components/utils/Components/SolicitudesActions/index.jsx

feat(solicitudes): fixed control documental

---

apps/siiges-app/pages/solicitudes/detallesSolicitudes/[id]/recepcionFormatos/index.jsx

feat(documentos): fixed control documental

---

packages/inspecciones/src/components/FormAsignacionInspecciones/ModalInspecciones/index.jsx

feat(inspecciones): fixed inspecciones issues

---

packages/inspecciones/src/components/FormAsignacionInspecciones/ModalInspecciones/index.jsx

feat(inspecciones): fixed inspecciones

---

packages/solicitudes/src/components/Sections/Asignaturas.jsx
packages/solicitudes/src/components/Sections/Mocks/Asignaturas/index.jsx
packages/solicitudes/src/components/Sections/Mocks/AsignaturasFormacionElectiva/index.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasFormacionModales/AsignaturasFormacionCreateModal.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasFormacionModales/AsignaturasFormacionEditModal.jsx

correccion soliditudes, ajustados los grados en asignaturas

feat(solicitudes): fixed asignaturas issues with grados

---

apps/siiges-app/pages/usuarios/consultar/[usuarioId]/index.jsx
apps/siiges-app/pages/usuarios/perfilUsuario/index.jsx

En la sección de usuarios, la pantalla de consultar usuario no tiene un título. Se agregó el título "Consultar Usuario" para mejorar la usabilidad y la consistencia de la interfaz.
Cambios realizados
Se actualizó el componente ConsultarUsuario para incluir el atributo title="Consultar Usuarios" en el componente Layout.
Antes:
Ahora:

Refactor(SDT-595): se agrego titulo

---

packages/shared/src/components/Input/InputTime.jsx
packages/shared/src/index.js
packages/solicitudes/src/components/ModuleHeader/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/index.jsx
packages/solicitudes/src/components/SectionLayout/ButtonSection.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasModales/AsignaturasCreateModal.jsx
packages/solicitudes/src/components/utils/Components/DiligenciasModales/DiligenciasFormModal.jsx
packages/solicitudes/src/components/utils/sections/errors/errorDatosDiligencias.js

correcciones de los botones de modulos en solicitudes

feat(solicitud): fixed module buttons plus an extra error

---

packages/solicitudes/src/components/utils/Components/DiligenciasModales/DiligenciasFormModal.jsx
packages/solicitudes/src/components/utils/Components/InfraestructuraModales/DeleteInfraestructura.jsx
packages/solicitudes/src/components/utils/Components/InfraestructuraModales/InfraestructuraEditModal.jsx
packages/solicitudes/src/components/utils/Components/InstitucionesAledanas.jsx
packages/solicitudes/src/components/utils/Components/InstitucionesAledanas/DeleteInstitucionesAledanas.jsx
packages/solicitudes/src/components/utils/Components/InstitucionesAledanas/InstitucionAledanaEditModal.jsx

fix(solicitudes): various fixes on modales of solicitudes

---

apps/siiges-app/pages/solicitudes/detallesSolicitudes/[id]/index.jsx
apps/siiges-app/pages/solicitudes/detallesSolicitudes/[id]/recepcionFormatos/index.jsx

- Descarga de oficio admisorio (Validación fechaRecepcion).

SDT-607: feature: Descarga de Oficio Admisorio, lógica.

---

packages/inspecciones/src/utils/getSolicitudesInspeccion.jsx

Solo debe mostrar las solicitudes con status 6 y 7 en el módulo Inspecciones.

SDT-611: fix: Solicitudes status 6 y 7.

---

packages/solicitudes/src/components/ModuleSelector/CambioDomicilio/index.jsx

- Cambio de domicilio.
- Selección de programa con estatusSolicitudId=11.
- Selección de plantel diferente al del que tiene asignado por defecto.

SDT-617: feature: Cambio de domicilio (Selección de programa y plantel)

---

packages/solicitudes/src/components/ModuleSelector/Refrendo/index.jsx

- Cambio del **endpoint** a **estatusSolicitudId=11**.

SDT-619: feature: Corrección refrendo (estatusSolicitudId=11)

---

packages/solicitudes/src/components/utils/Components/InfraestructuraModales/InfraestructuraEditModal.jsx

corrección editar infraestructuras

fix(solicitudes): fixed edit infraestructuras

---

packages/solicitudes/src/components/NuevaSolicitud/PlanEstudios/index.jsx
packages/solicitudes/src/components/SectionLayout/ButtonSection.jsx
packages/solicitudes/src/components/Sections/Asignaturas.jsx
packages/solicitudes/src/components/Sections/AsignaturasFormacionElectiva.jsx
packages/solicitudes/src/components/Sections/Curricula.jsx
packages/solicitudes/src/components/Sections/DatosPlanEstudios.jsx
packages/solicitudes/src/components/Sections/Docentes.jsx
packages/solicitudes/src/components/Sections/Egreso.jsx
packages/solicitudes/src/components/Sections/FundamentosPlanEstudios.jsx
packages/solicitudes/src/components/Sections/Hooks/useSectionDisabled.jsx
packages/solicitudes/src/components/Sections/Ingreso.jsx
packages/solicitudes/src/components/Sections/Observaciones.jsx
packages/solicitudes/src/components/Sections/TrayectoriaEducativa.jsx
packages/solicitudes/src/components/utils/Context/observacionesContext.jsx
packages/solicitudes/src/components/utils/submitEditSolicitud.jsx
packages/solicitudes/src/components/utils/submitNewSolicitud.jsx

added disabled logic to the sections

feat(solicitudes): added disabled logic

---

packages/serviciosEscolares/src/Components/Programas/ProgramasSections/Reglas.jsx

SDT-621: feature: Reglas (calificaciones)

---

packages/solicitudes/src/components/SectionLayout/ButtonSection.jsx
packages/solicitudes/src/components/utils/submitEditSolicitud.jsx
packages/solicitudes/src/components/utils/submitNewSolicitud.jsx

correcciones crear solicitudes

fix(solicitudes): fixed issues with create solicitudes

---

apps/siiges-app/pages/solicitudes/detallesSolicitudes/[id]/index.jsx
packages/instituciones/src/components/Planteles/PlantelEditForm/index.jsx
packages/instituciones/src/components/Planteles/PlantelNewForm/index.jsx
packages/instituciones/src/components/Planteles/PlantelView/index.jsx
packages/instituciones/src/components/utils/plantelErrors.js
packages/instituciones/src/components/utils/submitEditPlantel.js
packages/solicitudes/src/components/utils/Components/SolicitudesActions/index.jsx

Se hicieron cambios en:
- Planteles > Consultar los datos, algunos datos no eran mostrados.
- Planteles > Editar los datos, no editaba los datos.
- Solicitudes > Borrar una solicitud.
- Solicitudes > DetallesSolicitud > Botón de regresar.

SDT-651: fix: Observaciones para Planteles, Solicitudes, DetallesSolicitudes

---

apps/siiges-app/pages/notificaciones/index.jsx
packages/shared/src/components/Buttons/ButtonsForm.jsx
packages/shared/src/components/Navbar/MenuNavbar.jsx
packages/solicitudes/src/components/ModuleSelector/CambioDomicilio/index.jsx
packages/solicitudes/src/components/ModuleSelector/NuevaSolicitud/index.jsx
packages/solicitudes/src/components/ModuleSelector/Refrendo/index.jsx
packages/solicitudes/src/components/SectionLayout/ButtonSection.jsx
packages/solicitudes/src/components/Sections/AsignaturasFormacionElectiva.jsx
packages/solicitudes/src/components/utils/Components/SolicitudesActions/index.jsx

Se han corregido botones, secciones y titulos

SDT-649Fix: se corriegieron observaciones

---

packages/instituciones/src/components/Instituciones/InstitucionForm/index.jsx
packages/instituciones/src/components/Instituciones/InstitucionView/index.jsx
packages/instituciones/src/utils/institucionHandler.jsx
packages/solicitudes/src/components/SectionLayout/ButtonSection.jsx
packages/solicitudes/src/components/Sections/Asignaturas.jsx
packages/solicitudes/src/components/Sections/AsignaturasFormacionElectiva.jsx
packages/solicitudes/src/components/Sections/DatosPlantel.jsx
packages/solicitudes/src/components/Sections/Docentes.jsx
packages/solicitudes/src/components/Sections/Mocks/Asignaturas/index.jsx
packages/solicitudes/src/components/Sections/Mocks/AsignaturasFormacionElectiva/index.jsx
packages/solicitudes/src/components/Sections/Mocks/Docentes/index.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasButtons.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasFormacionButtons.jsx
packages/solicitudes/src/components/utils/Components/DocentesButtons.jsx
packages/solicitudes/src/components/utils/Components/DocentesModales/DocentesModal.jsx

Observaciones:
**Mi Institcición**
- Los nombres propuestos no deben repetirse.
- Información general de la institución debe estar en una pantalla.
- Datos del rector y Ratificación de nombre en otra pantalla.
- Botón para Regresar/Salir.
**Plan de Estudios (Sección 2 del Módulo 1 FDP01)**
- Al terminar la sección debe deshabilitar el registrar otro archivo.
**Plan de Estudios (Sección 6, 7  y 8 Módulo 1 Asignaturas y Docentes)**
- Deshabilitar el botón de “Agregar Asignatura”. 
- Solo mostrar la acción de consultar asignatura. 
- (Lo mismo para Asignaturas Selectivas y Docentes).
- En Docentes debe mostrar la formación profesional (No la muestra).
- Agregar número de páginas (Agregar Docente, Consultar Docente). 
- En Consultar Docente el botón “Anterior” moverlo un poco a la izquierda. …

SDT-654: fix: Observaciones, nombres propuestos, página doble para datos del rector, botón regresar, deshabilitar secciones.

---

packages/shared/src/components/Input/InputFile.jsx
packages/shared/src/utils/handlers/getFile.js

Arreglado el sistema de redireccionamiento que se utiliza en los enlaces de los archivos

fix(files): fixed url redirect on files

---

apps/siiges-app/pages/serviciosEscolares/solicitudesFolios/alumnos/[id]/certificados/index.jsx
apps/siiges-app/pages/serviciosEscolares/solicitudesFolios/alumnos/[id]/titulos/index.jsx
packages/serviciosEscolares/src/Components/Folios/ButtonsFolios/index.jsx
packages/serviciosEscolares/src/Components/Folios/FoliosData/index.jsx
packages/serviciosEscolares/src/Components/Folios/FoliosForm/index.jsx

varias correcciones y añadido el modal de confirmacion

feat(folios): added confirmation modal and fixed issues

---

packages/instituciones/src/components/Planteles/PlantelView/index.jsx

feat(plantel): added back button

---

apps/siiges-app/pages/serviciosEscolares/solicitudesFolios/[id]/certificados/index.jsx
apps/siiges-app/pages/serviciosEscolares/solicitudesFolios/[id]/titulos/index.jsx
apps/siiges-app/pages/serviciosEscolares/solicitudesFolios/admin/[id]/folios.jsx
apps/siiges-app/pages/serviciosEscolares/solicitudesFolios/alumnos/[id]/certificados/index.jsx
apps/siiges-app/pages/serviciosEscolares/solicitudesFolios/alumnos/[id]/titulos/index.jsx
apps/siiges-app/pages/serviciosEscolares/solicitudesFolios/createFolio/certificados/index.jsx
apps/siiges-app/pages/serviciosEscolares/solicitudesFolios/createFolio/titulos/index.jsx
packages/serviciosEscolares/src/Components/Folios/ButtonsFolios/index.jsx
packages/serviciosEscolares/src/Components/Folios/FoliosData/Modal/certificados.jsx
packages/serviciosEscolares/src/Components/Folios/FoliosData/index.jsx
packages/serviciosEscolares/src/Components/Folios/FoliosTable/adminTable.jsx
packages/serviciosEscolares/src/Components/Folios/FoliosTable/index.jsx
packages/shared/src/components/Submit/SubmitDocument.js

completadas las correcciones de folios

Sdt 679 - correcciones en folios

---

packages/instituciones/src/components/Instituciones/InstitucionForm/index.jsx
packages/users/src/components/Usuarios/UsuarioAvatar/index.jsx

Reverts subsesjal/siiges-ui#235

Revert "SDT-680: Cambiar imagen de perfil y de institucion"

---

packages/authentication/src/utils/submitNewLogin.js

Al parecer en el merge anterior hubo una omisión de este archivo y se envió vacío

SDT-698 bugfix: se cambio el fetch url que daba problemas

---

packages/solicitudes/src/components/Modal/ModalObservacion.jsx
packages/solicitudes/src/components/ModuleHeader/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/PlanEstudios/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/index.jsx
packages/solicitudes/src/components/SectionLayout/ButtonSection.jsx
packages/solicitudes/src/components/utils/submitTrayectoriaeducativa.jsx

correcciones en el calculo de la seccion actual del ticket SDT-630

fix(solicitudes): issues with calculating currentSection

---

packages/solicitudes/src/components/Modal/ModalObservacion.jsx

feat(solicitudes): buttons corrections

---

packages/serviciosEscolares/src/Components/Acreditacion/Calificaciones/index.jsx
packages/serviciosEscolares/src/Components/Acreditacion/DetallesAsignatura/index.jsx
packages/serviciosEscolares/src/Components/Alumnos/FormAlumno/DocumentosAlumno.jsx
packages/serviciosEscolares/src/Components/Alumnos/FormAlumno/dataAlumnos.js
packages/serviciosEscolares/src/Components/Alumnos/FormAlumno/index.jsx
packages/serviciosEscolares/src/Components/Inscripciones/InscripcionesTable/index.jsx
packages/serviciosEscolares/src/Components/Programas/ProgramasSections/ProgramasData.jsx
packages/serviciosEscolares/src/Components/Programas/ProgramasSections/Reglas.jsx
packages/serviciosEscolares/src/Components/Validacion/DatosInstitucion/index.jsx
packages/serviciosEscolares/src/Components/utils/ActionsAsignaturas.jsx
packages/serviciosEscolares/src/Components/utils/ModalAlumnosInscritos.jsx
packages/serviciosEscolares/src/Components/utils/ProgramasPDF.jsx
packages/serviciosEscolares/src/Tables/columnsAlumnosInscritos.jsx
packages/serviciosEscolares/src/Tables/columnsInscritosExtra.jsx
packages/serviciosEscolares/src/Tables/inscripcionesTable.jsx

**Programas:** 
- Archivos no se visualizan correctamente.
- Quitar objetivo general y particular.
- Reglas, no modifica la base de datos correctamente 
- Quitar el router.back del Guardar en reglas. 
**Agregar alumno**
- Como Control Escolar IES debería ser igual que con representante legal sin dejar la modificación la situación.
- Cuando agregas un alumno por defecto su situación es inactivo.
- Colocar un botón de salir (Editar Alumno en Documento).
**Validación**
- Problemas al subir documento de validación en datos de institución de procedencia y no aparece icono de cuando ya se subió el documento.
- Cancelar.
**Inscripción**
- No muestra nombre de asignatura.
- Si el alumno no está con validación de auténtico y no está como activo, no se puede inscribir.
- Consultar alumno te deja …

SDT 692: Servicios Escolares 1.

---

packages/opds/src/components/organosColegiados/Form/organosColegiados.jsx

acomodo de los campos de la sesiones de los organos colegiados, primero se envia la convocatoria junto con la orden del dia y por ultimo se realiza el acta

SDT-597 acomodoorganoscolegiados

---

packages/solicitudes/src/components/Modal/ModalOficio.jsx

Algo complicado no se los voy a negar

SDT-783: fix: estatusSolicitudId: 11 al generar acuerdo RVOE

---

apps/siiges-app/pages/serviciosEscolares/alumnos/[alumnoId]/HistorialAlumno/index.jsx
packages/serviciosEscolares/src/Components/Alumnos/AlumnosHistorial/index.jsx
packages/serviciosEscolares/src/Components/Alumnos/HistorialTable/index.jsx
packages/serviciosEscolares/src/Components/utils/ButtonAlumnos.jsx
packages/serviciosEscolares/src/Components/utils/alumnosService.js
packages/serviciosEscolares/src/Tables/historialAlumnosTable.jsx
packages/serviciosEscolares/src/index.js
packages/shared/src/components/Buttons/Button.jsx

Ta bien solo falta terminar el pdf para agregar el botón de descarga.

SDT-761: feat: Historial Académico

---

apps/siiges-app/pages/serviciosEscolares/solicitudesFolios/[id]/certificados/index.jsx
apps/siiges-app/pages/serviciosEscolares/solicitudesFolios/[id]/titulos/index.jsx
apps/siiges-app/pages/serviciosEscolares/solicitudesFolios/admin/[id]/folios.jsx
packages/instituciones/src/utils/getAlumnosByPrograma.jsx
packages/serviciosEscolares/src/Components/Folios/ButtonsFolios/index.jsx
packages/serviciosEscolares/src/Components/Folios/ButtonsFoliosAdmin/index.jsx
packages/serviciosEscolares/src/Components/Folios/FoliosData/Modal/certificados.jsx
packages/serviciosEscolares/src/Components/Folios/FoliosData/Modal/titulos.jsx
packages/serviciosEscolares/src/Components/Folios/FoliosData/index.jsx
packages/serviciosEscolares/src/Components/Folios/FoliosTable/adminTable.jsx
packages/serviciosEscolares/src/Components/Folios/FoliosTable/index.jsx
packages/shared/src/components/Alert/index.jsx
packages/shared/src/components/Buttons/Button.jsx
packages/shared/src/components/Buttons/ButtonsSections.jsx
packages/shared/src/components/Input/InputFile.jsx
packages/shared/src/components/LabelData/index.jsx

conexiones con el backend y correcciones de errores

Sdt 795 - Funcionalidad completada

---

packages/serviciosEscolares/src/Components/Inscripciones/InscripcionesForm/index.jsx

Dios me permite ser Senior Developer

SDT-797: fix: Arreglar error del fetch grupos

---

apps/siiges-app/pages/notificaciones/index.jsx
packages/shared/src/components/Navbar/MenuNavbar.jsx

- Agregar columna de Estatus en la tabla de Notificaciones.
- Quitar 'Ajustes' (El que lo vuelva a agregar lo voy a funar en Twitter).
- Notificaciones personalizadas para admin u otro usuario.
- Agregar un botón de "Regresar" para la notificación.

SDT-806: fix: Notificaciones

---

apps/siiges-app/pages/serviciosEscolares/servicioSocial/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/ServiciosSociales/SolicitudServSocFilter/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/ServiciosSociales/SolicitudesServSocForm/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/ServiciosSociales/SolicitudesServSocTable/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/ServiciosSociales/index.jsx
packages/serviciosEscolares/src/index.js

Módulo de Servicio Social.
- Muestra los 3 filtros (Instituciones, Planteles y Programas).
- Muestra la tabla con todas las solicitudes.
- Las acciones AÚN no están implementadas.

SDT-889: feat: Módulo de servicio social con sus filtros.

---

apps/siiges-app/pages/serviciosEscolares/index.jsx
packages/serviciosEscolares/src/Components/Validacion/DatosInstitucion/index.jsx

Añadi que los usuarios admin y ce_sicty puedan habilitar o deshabilitar para edicion las solicitudes de validacion

feat(validacion): added estatus manipulation

---

apps/siiges-app/pages/solicitudesBecas/crear/index.jsx
apps/siiges-app/pages/solicitudesBecas/editar/[solicitudBecasId]/index.jsx
apps/siiges-app/pages/solicitudesBecas/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/AlumnosSection/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/ButtonsBox/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/SolicitudBecasSection/DatosPlantel/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/SolicitudBecasSection/DatosPrograma/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/SolicitudBecasSection/DatosSolicitud/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/SolicitudBecasSection/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasFilter/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasTable/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/utils/index.jsx

SDT-874: Progress on create/edit Solicitud Becas module (incomplete)

---

apps/siiges-app/pages/solicitudesBecas/crear/index.jsx
apps/siiges-app/pages/solicitudesBecas/editar/[solicitudBecasId]/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/AlumnosSection/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/ButtonsBox/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/index.jsx
packages/users/src/utils/usuarioHandler.js

pagina de becas alumnos
modal de añadir alumno

feat(becas): add alumnos to becas

---

apps/siiges-app/pages/solicitudesBecas/consultar/[solicitudBecasId]/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/AlumnosSection/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/ButtonsBox/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/ButtonsReviewBox/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/SolicitudBecasSection/DatosSolicitud/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/SolicitudBecasSection/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasFilter/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasTable/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/utils/SolicitudesBecasTableButtons/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/utils/index.jsx
packages/shared/src/components/Drawer/utils/menuUsers.jsx
packages/shared/src/components/Select/index.jsx

vista principal usuario becas_sicyt
vista de la solicitud del usuario becas_sicyt

Sdt 904 - Correcciones en las pantallas y funciones de Becas

---

packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/AlumnosSection/index.jsx

Funcionalidad del conteo de becas:

feat(becas): added count of porcentajes becas

---

packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/AlumnosSection/index.jsx

Añadidas columnas de porcentaje y promedio

feat(becas): extra columns for alumnos

---

packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/AlumnosSection/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasTable/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/utils/SolicitudesBecasTableButtons/index.jsx

vista eliminar Beca
eliminar alumno

feat(becas): Delete functionality incorporated

---

packages/serviciosEscolares/src/Components/BecasServiciosSociales/Becas/SolicitudesBecasBox/SolicitudBecasSection/DatosSolicitud/index.jsx
packages/shared/src/components/Buttons/ButtonFile.jsx
packages/shared/src/utils/handlers/getFile.js

vista con el boton de generar pdf

feat(becas): added buton to generate beca pdf

---

packages/shared/src/components/Input/InputDate.jsx

fixed an issue that caused an error mesagge to be displayed when there was no error

fix(inputDate): fixed an issue on the input Date

---

packages/serviciosEscolares/src/Components/BecasServiciosSociales/ServiciosSociales/SolicitudServSocFilter/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/ServiciosSociales/SolicitudesServSocBox/AlumnosServicioSection/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/ServiciosSociales/SolicitudesServSocBox/index.jsx
packages/serviciosEscolares/src/Components/BecasServiciosSociales/ServiciosSociales/SolicitudesServSocTable/index.jsx
packages/shared/src/components/Drawer/utils/menuUsers.jsx

Sdt 921 - Seccion de alumnos en servicio social

---

apps/siiges-app/pages/solicitudes/index.jsx

SDT-941: funciono

---

packages/serviciosEscolares/src/Components/Acreditacion/Calificaciones/index.jsx
packages/serviciosEscolares/src/Components/Programas/ProgramasSections/Reglas.jsx

Añadidas validaciones a la seccion de "reglas" dentro de programas, y en acreditacion se añadio una notificacion en caso de que las reglas necesarias no esten completas o correctas

feat(programas): added validations to reglas

---

packages/shared/src/components/Drawer/utils/menuUsers.jsx
packages/solicitudes/src/components/Modal/ModalOficio.jsx

Sdt 959 - Correcciones del acuerdo Rvoe

---

packages/serviciosEscolares/src/Tables/alumnosTable.jsx
packages/shared/src/components/Input/InputFile.jsx
packages/shared/src/components/Navbar/index.jsx

Boton Pre-registro cambiado de color:
Añadida leyenda al campo de cargo de archivos:

fix(shared): miscellaneous changes

---

packages/serviciosEscolares/src/Components/Inscripciones/InscripcionesForm/Modals/CicloEscolarModal.jsx
packages/serviciosEscolares/src/Components/utils/CiclosEscolaresModal.jsx
packages/serviciosEscolares/src/Tables/ciclosEscolaresTable.jsx

fix(programa): ciclo escolar modal fields

---

packages/serviciosEscolares/src/Components/Inscripciones/InscripcionesForm/index.jsx

cambiada la alerta cuando no se encuentran datos:

fix(inscripcion): fixed alert when data wasnt found

---

packages/serviciosEscolares/src/Tables/inscripcionesTable.jsx

feat(inscripcion): added column to asignaturas

---

packages/instituciones/src/components/utils/getInstitucionUsuario.jsx
packages/solicitudes/src/components/NuevaSolicitud/DatosGenerales/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/Plantel/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/index.jsx
packages/solicitudes/src/components/Sections/DatosPlantel.jsx
packages/solicitudes/src/components/Sections/InstitucionData.jsx
packages/solicitudes/src/components/utils/Context/datosGeneralesContext.jsx
packages/solicitudes/src/components/utils/getPlantelesUsuario.jsx

modulos que antes no se renderizaban:

fix(solicitudes): fixed modules not being rendered correctly

---

packages/solicitudes/src/components/ModuleSelector/CambioDomicilio/index.jsx
packages/solicitudes/src/components/ModuleSelector/Refrendo/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/index.jsx

fix(solicitud): corrected label of tipo de solicitud

---

packages/solicitudes/src/components/utils/Components/AsignaturasButtons.jsx

fix(solicitudes): fixed consult button not showing in asignaturas

---

apps/siiges-app/pages/solicitudes/detallesSolicitudes/[id]/recepcionFormatos/index.jsx
packages/instituciones/src/components/Instituciones/InstitucionView/index.jsx
packages/shared/src/utils/handlers/getFile.js

refactor the getFile function for better error handling while maintaining legacy compatibility

Correcciones funcion getFile

---

packages/solicitudes/src/components/NuevaSolicitud/Plantel/index.jsx

fix(solicitudes): optimized rendering order to avoid conflicts

---

packages/serviciosEscolares/src/Components/Programas/ProgramasSections/ProgramasData.jsx

fix(programs): correccion de formato de fechas

---

apps/siiges-app/pages/autenticacion/recovery-password/[token]/index.jsx
packages/authentication/src/components/NewPassword/index.jsx
packages/authentication/src/index.js
packages/shared/src/utils/handlers/context.jsx

feat(auth): added recovery password functionality

---

apps/siiges-app/pages/tituloElectronico/[folio]/consultarFolio.jsx
apps/siiges-app/pages/tituloElectronico/index.jsx
packages/shared/src/utils/handlers/context.jsx

feat(tituloElectronico): added views for titulo electronico

---

packages/serviciosEscolares/src/Components/Alumnos/AlumnosTable/index.jsx
packages/serviciosEscolares/src/Components/utils/ButtonAlumnos.jsx
packages/serviciosEscolares/src/Tables/alumnosTable.jsx

**Botón para eliminar un alumno**
**_Usuarios válidos para eliminar:_**
admin
ce_sicyt

SDT-1085: feat: Boton de eliminar alumno

---

packages/serviciosEscolares/src/Components/Alumnos/FormAlumno/dataAlumnos.js
packages/serviciosEscolares/src/Components/Alumnos/FormAlumno/index.jsx

Reverts subsesjal/siiges-ui#523

Revert "feat(alumnos): added baja de alumno modal and logic"

---

apps/siiges-app/pages/serviciosEscolares/alumnos/[alumnoId]/EditarAlumno/index.jsx
packages/serviciosEscolares/src/Components/Alumnos/FormAlumno/ExpedienteAlumnos.jsx
packages/serviciosEscolares/src/Components/utils/alumnosService.js

SDT-1124(refactor): se agrego pestana de expediente en alumno para equivalencias

---

packages/serviciosEscolares/src/Components/Acreditacion/CalificacionesExtraordinarias/index.jsx
packages/serviciosEscolares/src/Tables/columnsInscritosExtra.jsx
packages/serviciosEscolares/src/Tables/columnsInscritosOrdinario.jsx

[SDT-1164](https://sicyt-projects.atlassian.net/browse/SDT-1164?atlOrigin=eyJpIjoiMTUzNTQxNTE3YjQ1NDQ2M2E4OTgzNzUyZDBjN2ZiMGYiLCJwIjoiaiJ9)
**Error al consultar calificaciones ordinarias y extraordinarias.**

SDT-1164: DEPLOY TO PROD

---

packages/serviciosEscolares/src/Utils/nombresCiclos.js

[SDT-1168](https://sicyt-projects.atlassian.net/browse/SDT-1168) -> Añadir ciclo 2025C

SDT-1168: DEPLOY TO PRODUCTION

---

.hooks/commit-msg
.hooks/pre-commit
.hooks/prepare-commit-msg
package.json

[SDT-1165](https://sicyt-projects.atlassian.net/browse/SDT-1165?atlOrigin=eyJpIjoiOGU5ODRmODk0MTg4NDQ5YTgyMDJmZjJmOGI5MWI5Y2EiLCJwIjoiaiJ9)
Se requiere ejecutar "yarn setup" para que quede funcionando, este PR automaticamente añadira el prefijo con el nombre de la rama a los commits, ej:
"añadido el setup de los prefijos en los commits" -> "SDT-1165: añadido el setup de los prefijos en los commits"

SDT-1165: DEPLOY TO PROD

---

packages/solicitudes/src/components/NuevaSolicitud/Anexos/index.jsx
packages/solicitudes/src/components/NuevaSolicitud/Plantel/index.jsx
packages/solicitudes/src/components/Sections/AnexosSeccion.jsx

[SDT-1182](https://sicyt-projects.atlassian.net/browse/SDT-1182?atlOrigin=eyJpIjoiM2E1YjUwYWMwOWZkNDRjOGEyNWRmZGQ2MmQ1NDVlZGMiLCJwIjoiaiJ9)
**_Filtrado de módulos, secciones y campos para refrendo en solicitudes._**

SDT-1182: DEPLOY TO PROD

---

apps/siiges-app/pages/solicitudes/index.jsx

[SDT-1184](https://sicyt-projects.atlassian.net/browse/SDT-1184?atlOrigin=eyJpIjoiYjk0NGVhZjg2ODc2NDQ2Y2FjY2YxODAwN2IwNTgwYzciLCJwIjoiaiJ9)
**_No se permite crear refrendo sin solicitud con RVOE._**

SDT-1184: DEPLOY TO PROD

---

.hooks/pre-commit
packages/serviciosEscolares/src/Components/Acreditacion/CalificacionesExtraordinarias/index.jsx
packages/serviciosEscolares/src/Components/utils/Calificaciones/CalificacionExtraInput.jsx

[SDT-1170](https://sicyt-projects.atlassian.net/browse/SDT-1170?atlOrigin=eyJpIjoiZTBiNzEzODAwYmJlNGJhNmJhOWE4N2Y4ODFkNTZmMmIiLCJwIjoiaiJ9)
Corrección de precommit.

SDT-1170: DEPLOY TO PROD

---

.hooks/pre-commit
packages/serviciosEscolares/src/Components/utils/AsignaturasEditModal.jsx
packages/solicitudes/src/components/utils/sections/errors/errorDatosAsignaturas.js

[SDT-1175](https://sicyt-projects.atlassian.net/browse/SDT-1175?atlOrigin=eyJpIjoiYjUzYTY3ZTJmZWFlNDY2YTg2MjU2OWI1M2U0MmUwNjgiLCJwIjoiaiJ9)
Corrección ciclosId en asignaturas de programa.
[Repo](https://github.com/subsesjal/siiges-ui/pull/595/commits)

SDT-1175-1: DEPLOY TO PROD

---

packages/serviciosEscolares/src/Components/utils/AsignaturasEditModal.jsx
packages/serviciosEscolares/src/Components/utils/Calificaciones/CalificacionExtraInput.jsx

[SDT-1175](https://sicyt-projects.atlassian.net/browse/SDT-1175?atlOrigin=eyJpIjoiYjUzYTY3ZTJmZWFlNDY2YTg2MjU2OWI1M2U0MmUwNjgiLCJwIjoiaiJ9)
Cambios de la rama 1179.
[Repo](https://github.com/subsesjal/siiges-ui/pull/598)

SDT-1175-2: DEPLOY TO PROD

---

packages/shared/src/components/Select/index.jsx
packages/solicitudes/src/components/Sections/Mocks/Asignaturas/index.jsx
packages/solicitudes/src/components/Sections/Mocks/AsignaturasFormacionElectiva/index.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasFormacionModales/AsignaturasFormacionCreateModal.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasFormacionModales/AsignaturasFormacionEditModal.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasModales/AsignaturasCreateModal.jsx
packages/solicitudes/src/components/utils/Components/AsignaturasModales/AsignaturasEditModal.jsx

[SDT-1210](https://sicyt-projects.atlassian.net/browse/SDT-1210?atlOrigin=eyJpIjoiNTE3YjFkOWJlYjhmNGY4ZjhlZWI2OWJmMzA5ZTNmNDgiLCJwIjoiaiJ9)
**_Corrección asignaturas en solicitudes._**

SDT-1210: DEPLOY TO PROD

---

packages/serviciosEscolares/src/Components/utils/ButtonsCiclosEscolares.jsx
packages/serviciosEscolares/src/Components/utils/DeleteCiclosEscolares.jsx

[SDT-1201](https://sicyt-projects.atlassian.net/browse/SDT-1201?atlOrigin=eyJpIjoiNWZlZGU5OTk5ODg0NDg2MmJiZmIxODJlYjMyMDc1MDkiLCJwIjoiaiJ9)
**_Se añadió botón de eliminación y mensajes alternativos en caso de tener grupos en ciclos escolares._**

SDT-1201: DEPLOY TO PROD

---

apps/siiges-app/pages/serviciosEscolares/programas/[id]/editPrograma.jsx
packages/serviciosEscolares/src/Components/Programas/ProgramasSections/Reglas.jsx

[SDT-1194](https://sicyt-projects.atlassian.net/browse/SDT-1194?atlOrigin=eyJpIjoiMmE0NDYwNTUxMTIxNDIxODgyNDljYzU0YWMyY2IwOWYiLCJwIjoiaiJ9)
**_Modificación en las reglas de los programas para que acepte decimales._**

SDT-1194: DEPLOY TO PROD
